mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as users_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('register/',users_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',users_views.profilepage,name='profile'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'),name='password_reset'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:id>/',views.detail,name='detail'),
    path('createproduct/',views.create_product,name='createproduct'),
    path('editproduct/<int:id>',views.edit_product,name='editproduct'),
    path('deleteproduct/<int:id>',views.delete_product,name='deleteproduct')
]

shop/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.FloatField()
    image = models.CharField(max_length=500, default='https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2xvdGhpbmclMjBzdG9yZXxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80')

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='uploads')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

shop/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name','description','price','image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

shop/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import ProductForm
from django.core.paginator import Paginator

# Create your views here.

def index(request):
    products = Product.objects.all()
    product_name=request.GET.get('product_name')

    #search code
    if product_name != '' and product_name is not None:
        products = products.filter(name__icontains=product_name)

    #paginator code
    paginator = Paginator(products,4)
    page = request.GET.get('page')
    products = paginator.get_page(page)

    return render(request,'shop/index.html',{'products':products})

def detail(request,id):
    product = Product.objects.get(id=id)
    return render(request,'shop/detail.html',{'product':product})

def create_product(request):
    if request.method == 'POST':
        product_form = ProductForm(request.POST)
        if product_form.is_valid():
            product_form.save()
            return redirect('shop:index')
    else:
        product_form = ProductForm()
    return render(request,'shop/create_form.html',{'product_form':product_form})

def edit_product(request,id):
    product = Product.objects.get(id=id)
    product_form = ProductForm(request.POST or None, instance=product)
    if product_form.is_valid():
        product_form.save()
        return redirect('shop:index')
    return render(request,'shop/create_form.html',{'product':product,'product_form':product_form})

def delete_product(request,id):
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        product.delete()
        return redirect('shop:index')
    return render(request,'shop/delete.html',{'product':product})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Hello {username} your account is created')
            return redirect('login')
    form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>
    <nav class="shadow-lg">
        <div class="flex flex-wrap justify-between ml-5 items-center mx-auto px-4 py-2.5">
            <a href="" class="flex items-center">
                <img class="h-9 mr-3" src="https://cdn1.iconfinder.com/data/icons/ecommerce-and-business-icon-set/256/shopping-bag.png" alt="">
                <span class="self-center text-xml font-semibold">City Collection</span>
            </a>
            <div class="flex items-center">
                <a href="{% url 'shop:createproduct' %}" class="mr-6 text-sm font-medium text-grey-500">Add Product</a>
                <a href="/shop/deleteproduct/{{product.id}}" class="mr-6 text-sm font-medium text-grey-500">Delete Product</a>
                <a href="/shop/editproduct/{{product.id}}" class="mr-6 text-sm font-medium text-grey-500">Edit Product</a>
                <a href="/shop/{{product.id}}" class="mr-6 text-sm font-medium text-grey-500">View Products</a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="mr-6 text-sm font-medium text-grey-500">Logout</a>
                <a href="{% url 'profile' %}" class="mr-6 text-sm font-medium text-grey-500">Profile</a>
                {% else %}
                <a href="{% url 'login' %}" class="mr-6 text-sm font-medium text-grey-500">Login</a>
                {% endif %}
                
            </div>
        </div>
    </nav>
    {% block body %}

    {% endblock %}
</body>
</html>

shop/templates/shop/create_form.html
{% extends 'shop/base.html' %} 
{% block body %}
<div class="flex flex-col justify-center items-center min-h-screen">
    <h1 class="font-bold text-lg">Create</h1>
     <form class="shadow-lg p-10" method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label >Name</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ product_form.name }}
            </div>
        </div>
        
        <div class="mb-2">
            <label >description</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ product_form.description }}
            </div>
        </div>

        <div class="mb-2">
            <label >Price</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ product_form.price }}
            </div>
        </div>

        <div class="mb-2">
            <label >Image</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ product_form.image }}
            </div>
        </div>

        <button class="bg-green-500 text-white px-4 py-2" type="submit">Add</button>
    </form>

</div>
   
{% endblock %}

shop/templates/shop/delete.html
<form method="post">
    {% csrf_token %}
    <h2>Are you sure want to delete '{{ product.name }}'</h2>
    <button type="submit">Confirm</button>
</form>

shop/templates/shop/detail.html
{% extends 'shop/base.html' %}
{% block body %}
<div class="flex p-10">
    <div>
      <img src="{{product.image}}" width="500px">
    </div>
    <div class="pl-10">
        <div class="text-4xl mb-4">{{ product.name }}</div>
        <div class="mb-4">{{ product.description }}</div>
        <div class="mb-4 text-green-700 font-bold">Rs {{ product.price }}</div>
        <div class="mt-4"><a class="mb-4 text-red-700 font-bold" href="#">Delete</a></div>
    <div>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block body %}
<div class="row">
    <div class="col-md-12">
        <form class="card card-sm">
            <div class="card-body row no-gutters align-items-center">
                <div class="col">
                    <input type="search" name="product_name" placeholder="Search for product" class="form-control form-control-borderless">
                </div>
                <div class="col-auto">
                    <button class="bg-indigo-500 text-white my-2 px-2 py-1" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="product-container flex">
{% for product in products %}
    <div class="product shadow-lg w-1/4 rounded-lg m-10">
        <div class="product-image">
            <img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2xvdGhpbmclMjBzdG9yZXxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80" alt="">
        </div>
        <div class="p-5">
            <div class="font-bold">
                {{ product.name }}
            </div>
            <div>
                {{ product.description }}
            </div>
            
            <div class="text-green-700 font-bold">
                Rs {{ product.price }}
            </div>
            <div class="mt-5">
                <a class="bg-green-500 text-white px-4 py-2" href="{% url 'shop:detail' product.id %}">View Details</a>
            </div>
        </div>

    </div>
{% endfor %}
</div>

<div class="row">
    <div class="col-md-3 offset-md-4">
        <ul class="pagination">
            {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
            </li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="?page={{ products.number }}">Current</a>
            </li>

            {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

<div class="text-green-500">
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'shop/base.html' %} 
{% block body %}
<div class="flex flex-col justify-center items-center min-h-screen">
    <h1 class="font-bold text-lg">🔐 Login</h1>
     <form class="shadow-lg p-10" method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label >Username</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ form.username }}
            </div>
        </div>
        
        <div class="mb-2">
            <label >Password</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ form.password }}
            </div>
        </div>

        <button class="bg-green-500 text-white px-4 py-2" type="submit">Login</button>
        <p>Forgot password? <a class="text-indigo-500" href="{% url 'password_reset' %}">Click here</a></p>
    </form>

    <p class="m-10"> New to the website? <span> <a class="text-indigo-500" href="{% url 'register' %}">Click here</a> to register</span></p>

</div>
   
{% endblock %}

users/templates/users/logout.html
<h1>The user has logged out successfully</h1>
<div class="text-green-500">
    <p class="m-10"><span> <a class="text-indigo-500" href="{% url 'login' %}">click here </a> to Login</span> </p>
</div>

users/templates/users/password_reset_complete.html
{% extends 'shop/base.html' %} 
{% block body %}
<h2>Your password has been successfully reset</h2>
{% endblock  %}

users/templates/users/password_reset_confirm.html
{% extends 'shop/base.html' %} 
{% block body %}
{% if validlink %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% else %}
<h2>Password reset link is invalid</h2>
{% endif %}
{% endblock  %}

users/templates/users/password_reset_done.html
{% extends 'shop/base.html' %} 
{% block body %}
<h2>We have mailed you the password reset link</h2>
{% endblock  %}

users/templates/users/password_reset_form.html
{% extends 'shop/base.html' %} 
{% block body %}
<h2 class="text-2xl m-10 font-bold">Reset your password By entering your Email </h2>
<div class="container py-5 mx-10">
    <form method="post" class="bg-white shadow-md m-10 px-8 rounded pt-6 pb-8 mb-4 w-4/5">
      {% csrf_token %} 
      <div class="mb-2">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">E-mail</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
          {{ form.email }}
        </div>
       </div>
      
       <button type="submit" class="bg-green-500 text-white my-5 px-5 py-2">Submit</button>
    </form>
    
</div>
{% endblock  %}

users/templates/users/profile.html
<h2>{{user.username}}</h2>
<img src="{{user.profile.image.url}}">

users/templates/users/register.html
{% extends 'shop/base.html' %} 
{% block body %}
<div class="flex flex-col justify-center items-center min-h-screen">
    <h1 class="font-bold text-lg">🔐 Register</h1>
     <form class="shadow-lg p-10" method="POST">
        {% csrf_token %}
        <div class="mb-2">
            <label >Username</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ form.username }}
            </div>
        </div>

        <div class="mb-2">
            <label >Email</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ form.email }}
            </div>
        </div>

        <div class="mb-2">
            <label >Password</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ form.password1 }}
            </div>
        </div>

        <div class="mb-2">
            <label >Confirm Password</label>
            <div class="border rounded py-2 px-2 mr-10">
                {{ form.password2 }}
            </div>
        </div>

        <button class="bg-green-500 text-white px-4 py-2" type="submit">Signup</button>

    </form>

    <p class="m-10">Alredy Register ? <span> <a class="text-indigo-500" href="{% url 'login' %}">click here </a> to login</span> </p>

</div>
{% endblock %}